package br.com.senac.integrador.escola.modelos.telas;

import br.com.senac.integrador.escola.modelos.Endereco;
import br.com.senac.integrador.modelos.enums.EstadoCivil;
import br.com.senac.integrador.escola.modelos.auxiliares.Manager;
import br.com.senac.integrador.escola.modelos.Pessoa;
import br.com.senac.integrador.escola.modelos.Professor;
import br.com.senac.integrador.escola.modelos.auxiliares.SQLManager;
import br.com.senac.integrador.escola.modelos.enums.CorRaca;
import br.com.senac.integrador.escola.modelos.enums.Genero;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeListener;

/**
 * Definicação da tela de cadastro de professores
 * @author Felipe Godinho Dal Molin
 */
public class CadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public CadastroProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesEstadoCivil = new javax.swing.ButtonGroup();
        grupoBotoesCorRaca = new javax.swing.ButtonGroup();
        grupoBotoesGenero = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        section = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        labelSection = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelEmpresa = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanelEstadoCivil = new javax.swing.JPanel();
        botaoSolteiro = new javax.swing.JRadioButton();
        botaoCasado = new javax.swing.JRadioButton();
        botaoDivorciado = new javax.swing.JRadioButton();
        botaoViuvo = new javax.swing.JRadioButton();
        titleEstadoCivil = new javax.swing.JLabel();
        jPanelEndereco = new javax.swing.JPanel();
        campoBairro = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        labelCidade2 = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        labelCidade1 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        jPanelPessoa = new javax.swing.JPanel();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        labelRG = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        labelDeficiencia = new javax.swing.JLabel();
        campoRG1 = new javax.swing.JTextField();
        jPanelFormacao = new javax.swing.JPanel();
        titleFormacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoFormacao = new javax.swing.JTextArea();
        botaoCadastrar = new javax.swing.JButton();
        jPanelCorRaca = new javax.swing.JPanel();
        botaoBranco = new javax.swing.JRadioButton();
        botaoPardo = new javax.swing.JRadioButton();
        botaoNegro = new javax.swing.JRadioButton();
        botaoAmarelo = new javax.swing.JRadioButton();
        botaoIndigena = new javax.swing.JRadioButton();
        titleCorRaca = new javax.swing.JLabel();
        jPanelGenero = new javax.swing.JPanel();
        botaoMasculino = new javax.swing.JRadioButton();
        botaoFeminino = new javax.swing.JRadioButton();
        botaoOutro = new javax.swing.JRadioButton();
        titleGenero = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        titleMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Professor");

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(92, 48, 115));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section.setBackground(new java.awt.Color(126, 35, 162));

        icon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/outline_account_circle_black_24dp.png"))); // NOI18N

        labelSection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSection.setText("Cadastrar");

        javax.swing.GroupLayout sectionLayout = new javax.swing.GroupLayout(section);
        section.setLayout(sectionLayout);
        sectionLayout.setHorizontalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(labelSection, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sectionLayout.setVerticalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelSection, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sidePanel.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, -1));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, 10));

        labelEmpresa.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmpresa.setText("Serasse");
        sidePanel.add(labelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, -1));

        background.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 790));

        content.setBackground(new java.awt.Color(126, 35, 162));
        content.setAutoscrolls(true);
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grupoBotoesEstadoCivil.add(botaoSolteiro);
        botaoSolteiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoSolteiro.setText("Solteiro(a)");

        grupoBotoesEstadoCivil.add(botaoCasado);
        botaoCasado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCasado.setText("Casado(a)");

        grupoBotoesEstadoCivil.add(botaoDivorciado);
        botaoDivorciado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoDivorciado.setText("Divorciado(a)");

        grupoBotoesEstadoCivil.add(botaoViuvo);
        botaoViuvo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoViuvo.setText("Viúvo(a)");

        titleEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleEstadoCivil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEstadoCivil.setText("Estado Civil");

        javax.swing.GroupLayout jPanelEstadoCivilLayout = new javax.swing.GroupLayout(jPanelEstadoCivil);
        jPanelEstadoCivil.setLayout(jPanelEstadoCivilLayout);
        jPanelEstadoCivilLayout.setHorizontalGroup(
            jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCivilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoDivorciado)
                    .addComponent(botaoSolteiro)
                    .addComponent(botaoCasado)
                    .addComponent(botaoViuvo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titleEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEstadoCivilLayout.setVerticalGroup(
            jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCivilLayout.createSequentialGroup()
                .addComponent(titleEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSolteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCasado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoDivorciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoViuvo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(jPanelEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        campoBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumero.setText("Número:");

        campoNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelCidade2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade2.setText("Endereço:");

        campoEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade.setText("Cidade:");

        campoCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelCidade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade1.setText("Estado:");

        campoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBairro.setText("Bairro:");

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(jPanelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        campoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        labelCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCPF.setText("CPF:");

        labelTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefone.setText("Telefone:");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setText("E-mail:");

        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        campoCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRG.setText("RG:");

        campoRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDeficiencia.setText("Deficiência:");

        campoRG1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelPessoaLayout = new javax.swing.GroupLayout(jPanelPessoa);
        jPanelPessoa.setLayout(jPanelPessoaLayout);
        jPanelPessoaLayout.setHorizontalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campoNome)
                        .addComponent(campoCPF)
                        .addComponent(campoTelefone)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelPessoaLayout.setVerticalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        content.add(jPanelPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        titleFormacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleFormacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleFormacao.setText("Formação");

        campoFormacao.setColumns(20);
        campoFormacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoFormacao.setRows(5);
        jScrollPane1.setViewportView(campoFormacao);

        javax.swing.GroupLayout jPanelFormacaoLayout = new javax.swing.GroupLayout(jPanelFormacao);
        jPanelFormacao.setLayout(jPanelFormacaoLayout);
        jPanelFormacaoLayout.setHorizontalGroup(
            jPanelFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
            .addComponent(titleFormacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFormacaoLayout.setVerticalGroup(
            jPanelFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormacaoLayout.createSequentialGroup()
                .addComponent(titleFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
        );

        content.add(jPanelFormacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        content.add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        grupoBotoesCorRaca.add(botaoBranco);
        botaoBranco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoBranco.setText("Branco");

        grupoBotoesCorRaca.add(botaoPardo);
        botaoPardo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoPardo.setText("Pardo");

        grupoBotoesCorRaca.add(botaoNegro);
        botaoNegro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoNegro.setText("Negro");

        grupoBotoesCorRaca.add(botaoAmarelo);
        botaoAmarelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAmarelo.setText("Amarelo");

        grupoBotoesCorRaca.add(botaoIndigena);
        botaoIndigena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoIndigena.setText("Indígena");

        titleCorRaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleCorRaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCorRaca.setText("Cor/raça");

        javax.swing.GroupLayout jPanelCorRacaLayout = new javax.swing.GroupLayout(jPanelCorRaca);
        jPanelCorRaca.setLayout(jPanelCorRacaLayout);
        jPanelCorRacaLayout.setHorizontalGroup(
            jPanelCorRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoPardo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoNegro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoAmarelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoIndigena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addComponent(titleCorRaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCorRacaLayout.setVerticalGroup(
            jPanelCorRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorRacaLayout.createSequentialGroup()
                .addComponent(titleCorRaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoBranco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPardo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNegro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAmarelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIndigena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(jPanelCorRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        grupoBotoesGenero.add(botaoMasculino);
        botaoMasculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoMasculino.setText("Masculino");

        grupoBotoesGenero.add(botaoFeminino);
        botaoFeminino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoFeminino.setText("Feminino");

        grupoBotoesGenero.add(botaoOutro);
        botaoOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoOutro.setText("Outro");

        titleGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleGenero.setText("Gênero");

        javax.swing.GroupLayout jPanelGeneroLayout = new javax.swing.GroupLayout(jPanelGenero);
        jPanelGenero.setLayout(jPanelGeneroLayout);
        jPanelGeneroLayout.setHorizontalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoMasculino, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(botaoFeminino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoOutro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGeneroLayout.setVerticalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneroLayout.createSequentialGroup()
                .addComponent(titleGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoOutro)
                .addContainerGap())
        );

        content.add(jPanelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 810, 420));

        title.setBackground(new java.awt.Color(92, 48, 115));

        titleMain.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMain.setText("Cadastrar Professor");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titleMain, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleMain, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 810, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        Component[] componentsPessoa = jPanelPessoa.getComponents();
        Component[] componentsEndereco = jPanelEndereco.getComponents();
        
        ArrayList<AbstractButton> buttonsEstadoCivil = Collections.list(grupoBotoesEstadoCivil.getElements());
        ArrayList<AbstractButton> buttonsCorRaca = Collections.list(grupoBotoesCorRaca.getElements());
        ArrayList<AbstractButton> buttonsGenero = Collections.list(grupoBotoesGenero.getElements());
        
        List<String> inputsPessoa = Manager.getListInputs(componentsPessoa);
        List<String> inputsEndereco = Manager.getListInputs(componentsEndereco);
        
        // Variáveis
        String nome = inputsPessoa.get(0);
        String cpf = inputsPessoa.get(1);
        String rg = inputsPessoa.get(2);
        String telefone = inputsPessoa.get(3);
        String email = inputsPessoa.get(4);
        String deficiencia = inputsPessoa.get(5);
        
        String estado = inputsEndereco.get(0);
        String cidade = inputsEndereco.get(1);
        String bairro = inputsEndereco.get(2);
        int numero = Integer.parseInt(inputsEndereco.get(3));
        String endereco = inputsEndereco.get(4);
        
        String formacao = campoFormacao.getText();
        String historicoProfissional = "DESIGN NÃO IMPLEMENTADO";
        
        boolean camposInvalidos = 
                nome.isBlank() ||
                cpf.isBlank() ||
                rg.isBlank() ||
                telefone.isBlank() ||
                email.isBlank() ||
                deficiencia.isBlank() ||
                estado.isBlank() ||
                cidade.isBlank() ||
                bairro.isBlank() ||
                numero <= 0 ||
                endereco.isBlank();
        try {
            if(camposInvalidos) {
                throw new IllegalArgumentException("Campos preenchidos incorretamente.");
            }
        } catch(IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        int indexEstadoCivil = Manager.getIndexOfButtonSelectByList(buttonsEstadoCivil);
        int indexCorRaca = Manager.getIndexOfButtonSelectByList(buttonsCorRaca);
        int indexGenero = Manager.getIndexOfButtonSelectByList(buttonsGenero);
        
        
        EstadoCivil estadoCivil = EstadoCivil.values()[indexEstadoCivil];
        Endereco ender = new Endereco(estado, cidade, bairro, numero, endereco);
        Genero genero = Genero.values()[indexGenero];
        CorRaca corRaca = CorRaca.values()[indexCorRaca];
        
        Pessoa pessoa = new Pessoa(nome, cpf, rg, telefone, email, deficiencia, estadoCivil, ender, genero, corRaca);
        Professor professor = new Professor(pessoa, formacao, historicoProfissional);
        
        try {
            SQLManager.cadastrarProfessor(professor);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProfessor().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JRadioButton botaoAmarelo;
    private javax.swing.JRadioButton botaoBranco;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JRadioButton botaoCasado;
    private javax.swing.JRadioButton botaoDivorciado;
    private javax.swing.JRadioButton botaoFeminino;
    private javax.swing.JRadioButton botaoIndigena;
    private javax.swing.JRadioButton botaoMasculino;
    private javax.swing.JRadioButton botaoNegro;
    private javax.swing.JRadioButton botaoOutro;
    private javax.swing.JRadioButton botaoPardo;
    private javax.swing.JRadioButton botaoSolteiro;
    private javax.swing.JRadioButton botaoViuvo;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextArea campoFormacao;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoRG1;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JPanel content;
    private javax.swing.ButtonGroup grupoBotoesCorRaca;
    private javax.swing.ButtonGroup grupoBotoesEstadoCivil;
    private javax.swing.ButtonGroup grupoBotoesGenero;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanelCorRaca;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelEstadoCivil;
    private javax.swing.JPanel jPanelFormacao;
    private javax.swing.JPanel jPanelGenero;
    private javax.swing.JPanel jPanelPessoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCidade1;
    private javax.swing.JLabel labelCidade2;
    private javax.swing.JLabel labelDeficiencia;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSection;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel section;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel title;
    private javax.swing.JLabel titleCorRaca;
    private javax.swing.JLabel titleEstadoCivil;
    private javax.swing.JLabel titleFormacao;
    private javax.swing.JLabel titleGenero;
    private javax.swing.JLabel titleMain;
    // End of variables declaration//GEN-END:variables
}