package br.com.senac.integrador.escola.modelos.telas;

import br.com.senac.integrador.escola.modelos.Endereco;
import br.com.senac.integrador.modelos.enums.EstadoCivil;
import br.com.senac.integrador.escola.modelos.auxiliares.Manager;
import br.com.senac.integrador.escola.modelos.Pessoa;
import br.com.senac.integrador.escola.modelos.Professor;
import br.com.senac.integrador.escola.modelos.auxiliares.Placeholder;
import br.com.senac.integrador.escola.modelos.auxiliares.Regex;
import br.com.senac.integrador.escola.modelos.auxiliares.SQLManager;
import br.com.senac.integrador.escola.modelos.enums.CorRaca;
import br.com.senac.integrador.escola.modelos.enums.Genero;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 * Definicação da tela de cadastro de professores
 * @author Felipe Godinho Dal Molin
 */
public class CadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public CadastroProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesEstadoCivil = new javax.swing.ButtonGroup();
        grupoBotoesCorRaca = new javax.swing.ButtonGroup();
        grupoBotoesGenero = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        section = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        labelSection = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanelEstadoCivil = new javax.swing.JPanel();
        botaoSolteiro = new javax.swing.JRadioButton();
        botaoCasado = new javax.swing.JRadioButton();
        botaoDivorciado = new javax.swing.JRadioButton();
        botaoViuvo = new javax.swing.JRadioButton();
        titleEstadoCivil = new javax.swing.JLabel();
        jPanelEndereco = new javax.swing.JPanel();
        campoBairro = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        labelCidade2 = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        labelCidade1 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        jPanelPessoa = new javax.swing.JPanel();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        labelRG = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        labelDeficiencia = new javax.swing.JLabel();
        campoDeficiencia = new javax.swing.JTextField();
        jPanelFormacao = new javax.swing.JPanel();
        titleFormacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoFormacao = new javax.swing.JTextArea();
        botaoCadastrar = new javax.swing.JButton();
        jPanelCorRaca = new javax.swing.JPanel();
        botaoBranco = new javax.swing.JRadioButton();
        botaoPardo = new javax.swing.JRadioButton();
        botaoNegro = new javax.swing.JRadioButton();
        botaoAmarelo = new javax.swing.JRadioButton();
        botaoIndigena = new javax.swing.JRadioButton();
        titleCorRaca = new javax.swing.JLabel();
        jPanelGenero = new javax.swing.JPanel();
        botaoMasculino = new javax.swing.JRadioButton();
        botaoFeminino = new javax.swing.JRadioButton();
        botaoOutro = new javax.swing.JRadioButton();
        titleGenero = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleHistoricoProfissional = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoHistoricoProfissional = new javax.swing.JTextArea();
        title = new javax.swing.JPanel();
        titleMain = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Professor");

        background.setBackground(new java.awt.Color(255, 255, 255));

        sidePanel.setBackground(new java.awt.Color(19, 16, 89));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section.setBackground(new java.awt.Color(19, 16, 89));
        section.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sectionMouseExited(evt);
            }
        });

        icon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/outline_account_circle_white_24dp.png"))); // NOI18N

        labelSection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSection.setForeground(new java.awt.Color(255, 255, 255));
        labelSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSection.setText("Cadastrar");

        javax.swing.GroupLayout sectionLayout = new javax.swing.GroupLayout(section);
        section.setLayout(sectionLayout);
        sectionLayout.setHorizontalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(labelSection, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sectionLayout.setVerticalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelSection, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sidePanel.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        content.setBackground(new java.awt.Color(75, 97, 148));
        content.setAutoscrolls(true);
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEstadoCivil.setBackground(new java.awt.Color(19, 16, 89));

        botaoSolteiro.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoSolteiro);
        botaoSolteiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoSolteiro.setForeground(new java.awt.Color(255, 255, 255));
        botaoSolteiro.setText("Solteiro(a)");

        botaoCasado.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoCasado);
        botaoCasado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCasado.setForeground(new java.awt.Color(255, 255, 255));
        botaoCasado.setText("Casado(a)");

        botaoDivorciado.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoDivorciado);
        botaoDivorciado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoDivorciado.setForeground(new java.awt.Color(255, 255, 255));
        botaoDivorciado.setText("Divorciado(a)");

        botaoViuvo.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoViuvo);
        botaoViuvo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoViuvo.setForeground(new java.awt.Color(255, 255, 255));
        botaoViuvo.setText("Viúvo(a)");

        titleEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        titleEstadoCivil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEstadoCivil.setText("Estado Civil");

        javax.swing.GroupLayout jPanelEstadoCivilLayout = new javax.swing.GroupLayout(jPanelEstadoCivil);
        jPanelEstadoCivil.setLayout(jPanelEstadoCivilLayout);
        jPanelEstadoCivilLayout.setHorizontalGroup(
            jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCivilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoDivorciado)
                    .addComponent(botaoSolteiro)
                    .addComponent(botaoCasado)
                    .addComponent(botaoViuvo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titleEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEstadoCivilLayout.setVerticalGroup(
            jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCivilLayout.createSequentialGroup()
                .addComponent(titleEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSolteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCasado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoDivorciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoViuvo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(jPanelEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        jPanelEndereco.setBackground(new java.awt.Color(19, 16, 89));

        campoBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoBairro.setForeground(new java.awt.Color(0, 0, 0));

        labelNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(255, 255, 255));
        labelNumero.setText("Número:");

        campoNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNumero.setForeground(new java.awt.Color(0, 0, 0));

        labelCidade2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade2.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade2.setText("Endereço:");

        campoEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEndereco.setForeground(new java.awt.Color(0, 0, 0));

        labelCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade.setText("Cidade:");

        campoCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCidade.setForeground(new java.awt.Color(0, 0, 0));

        labelCidade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade1.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade1.setText("Estado:");

        campoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEstado.setForeground(new java.awt.Color(153, 153, 153));
        campoEstado.setText("RS, SC, PR...");
        campoEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEstadoFocusLost(evt);
            }
        });

        labelBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBairro.setForeground(new java.awt.Color(255, 255, 255));
        labelBairro.setText("Bairro:");

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        content.add(jPanelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jPanelPessoa.setBackground(new java.awt.Color(19, 16, 89));

        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoTelefone.setForeground(new java.awt.Color(153, 153, 153));
        campoTelefone.setText("XX (XXX) XXXXX-XXXX");
        campoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusLost(evt);
            }
        });

        campoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(0, 0, 0));

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 255, 255));
        labelNome.setText("Nome:");

        labelCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(255, 255, 255));
        labelCPF.setText("CPF:");

        labelTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefone.setText("Telefone:");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail:");

        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNome.setForeground(new java.awt.Color(0, 0, 0));

        campoCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCPF.setForeground(new java.awt.Color(153, 153, 153));
        campoCPF.setText("XXX.XXX.XXX-XX");
        campoCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFFocusLost(evt);
            }
        });

        labelRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRG.setForeground(new java.awt.Color(255, 255, 255));
        labelRG.setText("RG:");

        campoRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoRG.setForeground(new java.awt.Color(153, 153, 153));
        campoRG.setText("X.XXX.XXX");
        campoRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoRGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRGFocusLost(evt);
            }
        });

        labelDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDeficiencia.setForeground(new java.awt.Color(255, 255, 255));
        labelDeficiencia.setText("Deficiência:");

        campoDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDeficiencia.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelPessoaLayout = new javax.swing.GroupLayout(jPanelPessoa);
        jPanelPessoa.setLayout(jPanelPessoaLayout);
        jPanelPessoaLayout.setHorizontalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoNome)
                    .addComponent(campoCPF)
                    .addComponent(campoTelefone)
                    .addComponent(campoEmail)
                    .addComponent(campoRG)
                    .addComponent(campoDeficiencia)))
        );
        jPanelPessoaLayout.setVerticalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        content.add(jPanelPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jPanelFormacao.setBackground(new java.awt.Color(19, 16, 89));

        titleFormacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleFormacao.setForeground(new java.awt.Color(255, 255, 255));
        titleFormacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleFormacao.setText("Formação");

        campoFormacao.setColumns(20);
        campoFormacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoFormacao.setForeground(new java.awt.Color(0, 0, 0));
        campoFormacao.setLineWrap(true);
        campoFormacao.setRows(5);
        jScrollPane1.setViewportView(campoFormacao);

        javax.swing.GroupLayout jPanelFormacaoLayout = new javax.swing.GroupLayout(jPanelFormacao);
        jPanelFormacao.setLayout(jPanelFormacaoLayout);
        jPanelFormacaoLayout.setHorizontalGroup(
            jPanelFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleFormacao, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(jPanelFormacaoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelFormacaoLayout.setVerticalGroup(
            jPanelFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormacaoLayout.createSequentialGroup()
                .addComponent(titleFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
        );

        content.add(jPanelFormacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 160));

        botaoCadastrar.setBackground(new java.awt.Color(19, 16, 89));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        content.add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, -1, -1));

        jPanelCorRaca.setBackground(new java.awt.Color(19, 16, 89));

        botaoBranco.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoBranco);
        botaoBranco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoBranco.setForeground(new java.awt.Color(255, 255, 255));
        botaoBranco.setText("Branco");

        botaoPardo.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoPardo);
        botaoPardo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoPardo.setForeground(new java.awt.Color(255, 255, 255));
        botaoPardo.setText("Pardo");

        botaoNegro.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoNegro);
        botaoNegro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoNegro.setForeground(new java.awt.Color(255, 255, 255));
        botaoNegro.setText("Negro");

        botaoAmarelo.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoAmarelo);
        botaoAmarelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAmarelo.setForeground(new java.awt.Color(255, 255, 255));
        botaoAmarelo.setText("Amarelo");

        botaoIndigena.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoIndigena);
        botaoIndigena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoIndigena.setForeground(new java.awt.Color(255, 255, 255));
        botaoIndigena.setText("Indígena");

        titleCorRaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleCorRaca.setForeground(new java.awt.Color(255, 255, 255));
        titleCorRaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCorRaca.setText("Cor/raça");

        javax.swing.GroupLayout jPanelCorRacaLayout = new javax.swing.GroupLayout(jPanelCorRaca);
        jPanelCorRaca.setLayout(jPanelCorRacaLayout);
        jPanelCorRacaLayout.setHorizontalGroup(
            jPanelCorRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoPardo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoNegro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoAmarelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoIndigena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addComponent(titleCorRaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCorRacaLayout.setVerticalGroup(
            jPanelCorRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorRacaLayout.createSequentialGroup()
                .addComponent(titleCorRaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoBranco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPardo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNegro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAmarelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIndigena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(jPanelCorRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jPanelGenero.setBackground(new java.awt.Color(19, 16, 89));

        botaoMasculino.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesGenero.add(botaoMasculino);
        botaoMasculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoMasculino.setForeground(new java.awt.Color(255, 255, 255));
        botaoMasculino.setText("Masculino");

        botaoFeminino.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesGenero.add(botaoFeminino);
        botaoFeminino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoFeminino.setForeground(new java.awt.Color(255, 255, 255));
        botaoFeminino.setText("Feminino");

        botaoOutro.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesGenero.add(botaoOutro);
        botaoOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoOutro.setForeground(new java.awt.Color(255, 255, 255));
        botaoOutro.setText("Outro");

        titleGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleGenero.setForeground(new java.awt.Color(255, 255, 255));
        titleGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleGenero.setText("Gênero");

        javax.swing.GroupLayout jPanelGeneroLayout = new javax.swing.GroupLayout(jPanelGenero);
        jPanelGenero.setLayout(jPanelGeneroLayout);
        jPanelGeneroLayout.setHorizontalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoMasculino, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(botaoFeminino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoOutro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGeneroLayout.setVerticalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneroLayout.createSequentialGroup()
                .addComponent(titleGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoOutro)
                .addContainerGap())
        );

        content.add(jPanelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(19, 16, 89));

        titleHistoricoProfissional.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleHistoricoProfissional.setForeground(new java.awt.Color(255, 255, 255));
        titleHistoricoProfissional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleHistoricoProfissional.setText("Histórico Profissional");

        campoHistoricoProfissional.setColumns(20);
        campoHistoricoProfissional.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoHistoricoProfissional.setForeground(new java.awt.Color(0, 0, 0));
        campoHistoricoProfissional.setRows(5);
        jScrollPane2.setViewportView(campoHistoricoProfissional);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleHistoricoProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleHistoricoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
        );

        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 340, 160));

        title.setBackground(new java.awt.Color(10, 23, 82));

        titleMain.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleMain.setForeground(new java.awt.Color(255, 255, 255));
        titleMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMain.setText("Cadastrar Professor");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleMain, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        
        ArrayList<AbstractButton> buttonsEstadoCivil = Collections.list(grupoBotoesEstadoCivil.getElements());
        ArrayList<AbstractButton> buttonsCorRaca = Collections.list(grupoBotoesCorRaca.getElements());
        ArrayList<AbstractButton> buttonsGenero = Collections.list(grupoBotoesGenero.getElements());
        
        String nome = campoNome.getText();
        String cpf = campoCPF.getText();
        String rg = campoRG.getText();
        String telefone = campoTelefone.getText();
        String email = campoEmail.getText();
        String deficiencia = campoDeficiencia.getText();
        
        String estado = campoEstado.getText();
        String cidade = campoCidade.getText();
        String bairro = campoBairro.getText();
        int numero;
        try {
            numero = Integer.parseInt(campoNumero.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        String endereco = campoEndereco.getText();
        
        String formacao = campoFormacao.getText();
        String historicoProfissional = campoHistoricoProfissional.getText();
        
        
        try {
            if(!cpf.matches(Regex.CPF)) {
                throw new IllegalArgumentException("CPF formatado incorretamente.");
            } else if(!telefone.matches(Regex.TELEFONE)) {
                throw new IllegalArgumentException("Telefone formatado incorretamente.");
            } else if(!rg.matches(Regex.RG)) {
                throw new IllegalArgumentException("RG formatado incorretamente.");
            } else if(!(estado.length() == 2)) {
                throw new IllegalArgumentException("Estado formatado incorretamente.");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        
        boolean camposInvalidos = 
                nome.isBlank() ||
                cpf.isBlank() ||
                rg.isBlank() ||
                telefone.isBlank() ||
                email.isBlank() ||
                deficiencia.isBlank() ||
                estado.isBlank() ||
                cidade.isBlank() ||
                bairro.isBlank() ||
                numero <= 0 ||
                endereco.isBlank() ||
                historicoProfissional.isBlank();
        try {
            if(camposInvalidos) {
                throw new IllegalArgumentException("Há campos preenchidos incorretamente.");
            }
        } catch(IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.out.println(telefone);
        int indexEstadoCivil = Manager.getIndexOfButtonSelectByList(buttonsEstadoCivil);
        int indexCorRaca = Manager.getIndexOfButtonSelectByList(buttonsCorRaca);
        int indexGenero = Manager.getIndexOfButtonSelectByList(buttonsGenero);
        
        
        EstadoCivil estadoCivil = EstadoCivil.values()[indexEstadoCivil];
        Endereco ender = new Endereco(estado, cidade, bairro, numero, endereco);
        Genero genero = Genero.values()[indexGenero];
        CorRaca corRaca = CorRaca.values()[indexCorRaca];
        
        Pessoa pessoa = new Pessoa(nome, cpf, rg, telefone, email, deficiencia, estadoCivil, ender, genero, corRaca);
        Professor professor = new Professor(pessoa, formacao, historicoProfissional);
        
        try {
            SQLManager.cadastrarProfessor(professor);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed
    private void campoFocusGained(java.awt.event.FocusEvent evt, javax.swing.JTextField textField, String placeholder) {
        if(textField.getText().equals(placeholder)) {
            textField.setText("");
        }
        textField.setForeground(Color.BLACK);
    }
    private void campoFocusLost(java.awt.event.FocusEvent evt, javax.swing.JTextField textField, String placeholder) {
        if(textField.getText().isBlank()) {
            textField.setText(placeholder);
            textField.setForeground(new Color(153,153,153));
            return;
        }
        textField.setForeground(Color.BLACK);
    }
    
    /**
     * Altera a cor do item do sidePanel quando o mouse passa em cima.
     * @param evt 
     */
    private void sectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectionMouseEntered
        section.setBackground(new Color(15, 34, 61));
    }//GEN-LAST:event_sectionMouseEntered
    /**
     * Retorna para a cor original do item do sidePanel quando o mouse sai de cima dele.
     * @param evt 
     */
    private void sectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectionMouseExited
        section.setBackground(new Color(19, 16, 89));
    }//GEN-LAST:event_sectionMouseExited
    
    private void campoTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusGained
        campoFocusGained(evt, campoTelefone, Placeholder.TELEFONE);
    }//GEN-LAST:event_campoTelefoneFocusGained

    private void campoTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusLost
        campoFocusLost(evt, campoTelefone, Placeholder.TELEFONE);
    }//GEN-LAST:event_campoTelefoneFocusLost

    private void campoCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusGained
        campoFocusGained(evt, campoCPF, Placeholder.CPF);
    }//GEN-LAST:event_campoCPFFocusGained

    private void campoCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusLost
        campoFocusLost(evt, campoCPF, Placeholder.CPF);
    }//GEN-LAST:event_campoCPFFocusLost

    private void campoRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGFocusGained
        campoFocusGained(evt, campoRG, Placeholder.RG);
    }//GEN-LAST:event_campoRGFocusGained

    private void campoRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGFocusLost
        campoFocusLost(evt, campoRG, Placeholder.RG);
    }//GEN-LAST:event_campoRGFocusLost

    private void campoEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEstadoFocusGained
        campoFocusGained(evt, campoEstado, Placeholder.ESTADO);
    }//GEN-LAST:event_campoEstadoFocusGained

    private void campoEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEstadoFocusLost
        campoFocusLost(evt, campoEstado, Placeholder.ESTADO);
    }//GEN-LAST:event_campoEstadoFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JRadioButton botaoAmarelo;
    private javax.swing.JRadioButton botaoBranco;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JRadioButton botaoCasado;
    private javax.swing.JRadioButton botaoDivorciado;
    private javax.swing.JRadioButton botaoFeminino;
    private javax.swing.JRadioButton botaoIndigena;
    private javax.swing.JRadioButton botaoMasculino;
    private javax.swing.JRadioButton botaoNegro;
    private javax.swing.JRadioButton botaoOutro;
    private javax.swing.JRadioButton botaoPardo;
    private javax.swing.JRadioButton botaoSolteiro;
    private javax.swing.JRadioButton botaoViuvo;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoDeficiencia;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextArea campoFormacao;
    private javax.swing.JTextArea campoHistoricoProfissional;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JPanel content;
    private javax.swing.ButtonGroup grupoBotoesCorRaca;
    private javax.swing.ButtonGroup grupoBotoesEstadoCivil;
    private javax.swing.ButtonGroup grupoBotoesGenero;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCorRaca;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelEstadoCivil;
    private javax.swing.JPanel jPanelFormacao;
    private javax.swing.JPanel jPanelGenero;
    private javax.swing.JPanel jPanelPessoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCidade1;
    private javax.swing.JLabel labelCidade2;
    private javax.swing.JLabel labelDeficiencia;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSection;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel section;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel title;
    private javax.swing.JLabel titleCorRaca;
    private javax.swing.JLabel titleEstadoCivil;
    private javax.swing.JLabel titleFormacao;
    private javax.swing.JLabel titleGenero;
    private javax.swing.JLabel titleHistoricoProfissional;
    private javax.swing.JLabel titleMain;
    // End of variables declaration//GEN-END:variables
}