/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.integrador.escola.modelos.telas.tela_aluno;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Jonathan
 */
public class page_perfil extends javax.swing.JInternalFrame {
    int idPessoa;
    int idEstudante;
    
    /**
     * Creates new form Inicio
     */
    public page_perfil() throws SQLException {
        initComponents();
        getInfo(1,1);
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_perfil = new javax.swing.JPanel();
        nasc_label = new javax.swing.JLabel();
        nacio_label = new javax.swing.JLabel();
        esco_label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        email_field = new javax.swing.JLabel();
        estado_field = new javax.swing.JLabel();
        fone_field = new javax.swing.JLabel();
        cidade_field = new javax.swing.JLabel();
        endereco_field = new javax.swing.JLabel();
        nasc_field = new javax.swing.JLabel();
        nacio_field = new javax.swing.JLabel();
        esco_field = new javax.swing.JLabel();
        estadoCivil_field = new javax.swing.JLabel();
        genero_field = new javax.swing.JLabel();
        defi_field = new javax.swing.JLabel();
        trab_field = new javax.swing.JLabel();
        resp_field = new javax.swing.JLabel();
        insc_field = new javax.swing.JLabel();
        matr_label = new javax.swing.JLabel();
        matr_field = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(590, 480));

        tab_perfil.setBackground(new java.awt.Color(67, 148, 222));
        tab_perfil.setPreferredSize(new java.awt.Dimension(590, 480));

        nasc_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nasc_label.setForeground(new java.awt.Color(255, 255, 255));
        nasc_label.setText("Data de Nascimento:");

        nacio_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nacio_label.setForeground(new java.awt.Color(255, 255, 255));
        nacio_label.setText("Nacionalidade:");

        esco_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        esco_label.setForeground(new java.awt.Color(255, 255, 255));
        esco_label.setText("Escolaridade:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Estado Civil:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gênero:");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Deficiência:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Trabalha:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Responsável:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Data de Inscrição:");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email:");

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Telefone:");

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Estado:");

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Cidade:");

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Endereço:");

        email_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        email_field.setForeground(new java.awt.Color(255, 255, 255));
        email_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        email_field.setText(" ");

        estado_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        estado_field.setForeground(new java.awt.Color(255, 255, 255));
        estado_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        estado_field.setText(" ");

        fone_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        fone_field.setForeground(new java.awt.Color(255, 255, 255));
        fone_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fone_field.setText(" ");

        cidade_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cidade_field.setForeground(new java.awt.Color(255, 255, 255));
        cidade_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cidade_field.setText(" ");

        endereco_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        endereco_field.setForeground(new java.awt.Color(255, 255, 255));
        endereco_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        endereco_field.setText(" ");

        nasc_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nasc_field.setForeground(new java.awt.Color(255, 255, 255));
        nasc_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nasc_field.setText(" ");

        nacio_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nacio_field.setForeground(new java.awt.Color(255, 255, 255));
        nacio_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nacio_field.setText(" ");

        esco_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        esco_field.setForeground(new java.awt.Color(255, 255, 255));
        esco_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        esco_field.setText(" ");

        estadoCivil_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        estadoCivil_field.setForeground(new java.awt.Color(255, 255, 255));
        estadoCivil_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        estadoCivil_field.setText(" ");

        genero_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        genero_field.setForeground(new java.awt.Color(255, 255, 255));
        genero_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genero_field.setText(" ");

        defi_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        defi_field.setForeground(new java.awt.Color(255, 255, 255));
        defi_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        defi_field.setText(" ");

        trab_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        trab_field.setForeground(new java.awt.Color(255, 255, 255));
        trab_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        trab_field.setText(" ");

        resp_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        resp_field.setForeground(new java.awt.Color(255, 255, 255));
        resp_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resp_field.setText(" ");

        insc_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        insc_field.setForeground(new java.awt.Color(255, 255, 255));
        insc_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        insc_field.setText(" ");

        matr_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        matr_label.setForeground(new java.awt.Color(255, 255, 255));
        matr_label.setText("Matrícula:");

        matr_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        matr_field.setForeground(new java.awt.Color(255, 255, 255));
        matr_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        matr_field.setText(" ");

        javax.swing.GroupLayout tab_perfilLayout = new javax.swing.GroupLayout(tab_perfil);
        tab_perfil.setLayout(tab_perfilLayout);
        tab_perfilLayout.setHorizontalGroup(
            tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_perfilLayout.createSequentialGroup()
                        .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(88, 88, 88)
                        .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fone_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tab_perfilLayout.createSequentialGroup()
                        .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(nasc_label)
                            .addComponent(nacio_label)
                            .addComponent(esco_label)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(matr_label))
                        .addGap(15, 15, 15)
                        .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matr_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insc_field, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(estado_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cidade_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(endereco_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nasc_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nacio_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(esco_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estadoCivil_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genero_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(defi_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trab_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resp_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        tab_perfilLayout.setVerticalGroup(
            tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matr_label)
                    .addComponent(matr_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(insc_field))
                .addGap(18, 18, 18)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(email_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(fone_field))
                .addGap(18, 18, 18)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(estado_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cidade_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(endereco_field))
                .addGap(18, 18, 18)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nasc_label)
                    .addComponent(nasc_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacio_label)
                    .addComponent(nacio_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_perfilLayout.createSequentialGroup()
                        .addComponent(esco_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(tab_perfilLayout.createSequentialGroup()
                        .addComponent(esco_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoCivil_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genero_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defi_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trab_field)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(resp_field))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static boolean isSQLSet = false;
    private static Connection connection;
    
    private static Connection createConnection() throws SQLException {
        if(isSQLSet) {
            return connection;
        }
        //String username = JOptionPane.showInputDialog("Insira o usuário do banco de dados.");
        //String password = JOptionPane.showInputDialog("Insira a senha do banco de dados.");
        
        String username = "root";
        String password = "inserida";
        
        String url = "jdbc:mysql://localhost/appescola";
        isSQLSet = true;
        connection = DriverManager.getConnection(url, username, password);
        return connection;
    }
     
    private void getInfo(int idPessoa, int idEndereco) throws SQLException {        
        connection = createConnection();
        Statement statement_pes = connection.createStatement();
        Statement statement_est = connection.createStatement();
        Statement statement_end = connection.createStatement();
        
        ResultSet dados = statement_pes.executeQuery("SELECT * from pessoa where idPessoa = " + idPessoa);
        ResultSet dados_est = statement_est.executeQuery("SELECT * from estudante where idPessoa = " + idPessoa);
        ResultSet dados_end = statement_end.executeQuery("SELECT * from endereco where idEndereco = " + idEndereco);

        dados.next();
        dados_est.next();
        dados_end.next();
        
        String endereco_BN = (dados_end.getString("bairro")) + " " + dados_end.getString("numero");
        
        matr_field.setText(dados_est.getString("idEstudante"));
        insc_field.setText(dados_est.getString("dataInscricao"));
        email_field.setText(dados.getString("email"));
        fone_field.setText(dados.getString("telefone"));
        estado_field.setText(dados_end.getString("estado"));
        cidade_field.setText(dados_end.getString("cidade"));
        endereco_field.setText(endereco_BN);
        nasc_field.setText(dados_est.getString("dataNascimento"));
        nacio_field.setText(dados.getString("nacionalidade"));
        esco_field.setText(dados_est.getString("escolaridade"));
        estadoCivil_field.setText(dados.getString("estadoCivil"));
        genero_field.setText(dados.getString("genero"));
        defi_field.setText(dados.getString("deficiencia"));
        resp_field.setText(dados_est.getString("nomeResponsavel"));
        
        if (dados_est.getString("trabalha") == "1") 
        {
            trab_field.setText("Sim");
        }
        else 
        {
            trab_field.setText("Não");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cidade_field;
    private javax.swing.JLabel defi_field;
    private javax.swing.JLabel email_field;
    private javax.swing.JLabel endereco_field;
    private javax.swing.JLabel esco_field;
    private javax.swing.JLabel esco_label;
    private javax.swing.JLabel estadoCivil_field;
    private javax.swing.JLabel estado_field;
    private javax.swing.JLabel fone_field;
    private javax.swing.JLabel genero_field;
    private javax.swing.JLabel insc_field;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel matr_field;
    private javax.swing.JLabel matr_label;
    private javax.swing.JLabel nacio_field;
    private javax.swing.JLabel nacio_label;
    private javax.swing.JLabel nasc_field;
    private javax.swing.JLabel nasc_label;
    private javax.swing.JLabel resp_field;
    private javax.swing.JPanel tab_perfil;
    private javax.swing.JLabel trab_field;
    // End of variables declaration//GEN-END:variables
}
