/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.integrador.escola.modelos.telas.tela_aluno;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Jonathan
 */
public class page_desempenho extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inicio
     */
    public page_desempenho() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_desempenho = new javax.swing.JPanel();
        comboBox_Ano = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_desempenho = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(590, 450));

        tab_desempenho.setBackground(new java.awt.Color(94, 113, 171));
        tab_desempenho.setPreferredSize(new java.awt.Dimension(590, 423));

        comboBox_Ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        table_desempenho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_desempenho.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        table_desempenho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Artes", null, null, null, null, null, null, null, null},
                {"Biologia", null, null, null, null, null, null, null, null},
                {"Ed. Física", null, null, null, null, null, null, null, null},
                {"Filosofia", null, null, null, null, null, null, null, null},
                {"Física", null, null, null, null, null, null, null, null},
                {"Geografia", null, null, null, null, null, null, null, null},
                {"História", null, null, null, null, null, null, null, null},
                {"Inglês", null, null, null, null, null, null, null, null},
                {"Literatura", null, null, null, null, null, null, null, null},
                {"Mat", null, null, null, null, null, null, null, null},
                {"Português", null, null, null, null, null, null, null, null},
                {"Química", null, null, null, null, null, null, null, null},
                {"Sociologia", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "1º Tri", "F", "2º Tri", "F", "3º Tri", "F", "Média Final", "F"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_desempenho.setGridColor(new java.awt.Color(0, 0, 0));
        table_desempenho.setShowGrid(true);
        jScrollPane1.setViewportView(table_desempenho);
        if (table_desempenho.getColumnModel().getColumnCount() > 0) {
            table_desempenho.getColumnModel().getColumn(0).setPreferredWidth(45);
            table_desempenho.getColumnModel().getColumn(1).setPreferredWidth(50);
            table_desempenho.getColumnModel().getColumn(2).setPreferredWidth(30);
            table_desempenho.getColumnModel().getColumn(3).setPreferredWidth(50);
            table_desempenho.getColumnModel().getColumn(4).setPreferredWidth(30);
            table_desempenho.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_desempenho.getColumnModel().getColumn(6).setPreferredWidth(30);
            table_desempenho.getColumnModel().getColumn(7).setPreferredWidth(50);
            table_desempenho.getColumnModel().getColumn(8).setPreferredWidth(30);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Situação:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aprovado");

        javax.swing.GroupLayout tab_desempenhoLayout = new javax.swing.GroupLayout(tab_desempenho);
        tab_desempenho.setLayout(tab_desempenhoLayout);
        tab_desempenhoLayout.setHorizontalGroup(
            tab_desempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_desempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_desempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(tab_desempenhoLayout.createSequentialGroup()
                        .addGroup(tab_desempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tab_desempenhoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 447, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab_desempenhoLayout.setVerticalGroup(
            tab_desempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_desempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBox_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_desempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_desempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_desempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox_Ano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tab_desempenho;
    private javax.swing.JTable table_desempenho;
    // End of variables declaration//GEN-END:variables
}
