/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.integrador.escola.modelos.telas.tela_aluno;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jonathan
 */
public class Tela_Aluno extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Aluno
     */
    public Tela_Aluno() {
        initComponents();
        open_page(inicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_fixed_bar = new javax.swing.JPanel();
        top_bar_name = new javax.swing.JLabel();
        top_bar_class = new javax.swing.JLabel();
        button_close = new javax.swing.JLabel();
        button_logout = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        nav_inicio = new javax.swing.JPanel();
        label_inicio = new javax.swing.JLabel();
        nav_desempenho = new javax.swing.JPanel();
        label_desempenho = new javax.swing.JLabel();
        nav_frequencia = new javax.swing.JPanel();
        label_frequencia = new javax.swing.JLabel();
        nav_ocorrencias = new javax.swing.JPanel();
        label_ocorrencias1 = new javax.swing.JLabel();
        nav_perfil = new javax.swing.JPanel();
        label_ocorrencias2 = new javax.swing.JLabel();
        nav_contato = new javax.swing.JPanel();
        label_ocorrencias3 = new javax.swing.JLabel();
        nav_material = new javax.swing.JPanel();
        label_ocorrencias4 = new javax.swing.JLabel();
        renderer = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        top_fixed_bar.setBackground(new java.awt.Color(10, 23, 82));
        top_fixed_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                top_fixed_barMouseDragged(evt);
            }
        });
        top_fixed_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                top_fixed_barMousePressed(evt);
            }
        });

        top_bar_name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        top_bar_name.setForeground(new java.awt.Color(255, 255, 255));
        top_bar_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top_bar_name.setText("Jonathan da Silva");

        top_bar_class.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        top_bar_class.setForeground(new java.awt.Color(255, 255, 255));
        top_bar_class.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top_bar_class.setText("Turma 506");

        button_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_close.png"))); // NOI18N
        button_close.setText("jLabel1");
        button_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_closeMouseClicked(evt);
            }
        });

        button_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_logout.png"))); // NOI18N
        button_logout.setText("jLabel2");
        button_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout top_fixed_barLayout = new javax.swing.GroupLayout(top_fixed_bar);
        top_fixed_bar.setLayout(top_fixed_barLayout);
        top_fixed_barLayout.setHorizontalGroup(
            top_fixed_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_fixed_barLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(top_fixed_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(top_bar_class, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(top_bar_name, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        top_fixed_barLayout.setVerticalGroup(
            top_fixed_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(top_fixed_barLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(top_bar_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(top_bar_class)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, top_fixed_barLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(top_fixed_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(top_fixed_bar);
        top_fixed_bar.setBounds(0, 0, 730, 80);

        navbar.setBackground(new java.awt.Color(19, 16, 89));

        nav_inicio.setBackground(new java.awt.Color(19, 16, 89));
        nav_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_inicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_inicioMouseExited(evt);
            }
        });

        label_inicio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_inicio.setForeground(new java.awt.Color(255, 255, 255));
        label_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_inicio.png"))); // NOI18N
        label_inicio.setText("Início");

        javax.swing.GroupLayout nav_inicioLayout = new javax.swing.GroupLayout(nav_inicio);
        nav_inicio.setLayout(nav_inicioLayout);
        nav_inicioLayout.setHorizontalGroup(
            nav_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nav_inicioLayout.setVerticalGroup(
            nav_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_inicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_inicio)
                .addContainerGap())
        );

        nav_desempenho.setBackground(new java.awt.Color(19, 16, 89));
        nav_desempenho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_desempenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_desempenhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_desempenhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_desempenhoMouseExited(evt);
            }
        });

        label_desempenho.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_desempenho.setForeground(new java.awt.Color(255, 255, 255));
        label_desempenho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_desempenho.png"))); // NOI18N
        label_desempenho.setText("Desempenho");

        javax.swing.GroupLayout nav_desempenhoLayout = new javax.swing.GroupLayout(nav_desempenho);
        nav_desempenho.setLayout(nav_desempenhoLayout);
        nav_desempenhoLayout.setHorizontalGroup(
            nav_desempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_desempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_desempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        nav_desempenhoLayout.setVerticalGroup(
            nav_desempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_desempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_desempenho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_frequencia.setBackground(new java.awt.Color(19, 16, 89));
        nav_frequencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_frequencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_frequenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_frequenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_frequenciaMouseExited(evt);
            }
        });

        label_frequencia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_frequencia.setForeground(new java.awt.Color(255, 255, 255));
        label_frequencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_frequencia.png"))); // NOI18N
        label_frequencia.setText("Frequência");

        javax.swing.GroupLayout nav_frequenciaLayout = new javax.swing.GroupLayout(nav_frequencia);
        nav_frequencia.setLayout(nav_frequenciaLayout);
        nav_frequenciaLayout.setHorizontalGroup(
            nav_frequenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_frequenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_frequencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        nav_frequenciaLayout.setVerticalGroup(
            nav_frequenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_frequenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_frequencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_ocorrencias.setBackground(new java.awt.Color(19, 16, 89));
        nav_ocorrencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_ocorrencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_ocorrenciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_ocorrenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_ocorrenciasMouseExited(evt);
            }
        });

        label_ocorrencias1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_ocorrencias1.setForeground(new java.awt.Color(255, 255, 255));
        label_ocorrencias1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_ocorrencias.png"))); // NOI18N
        label_ocorrencias1.setText("Ocorrências");

        javax.swing.GroupLayout nav_ocorrenciasLayout = new javax.swing.GroupLayout(nav_ocorrencias);
        nav_ocorrencias.setLayout(nav_ocorrenciasLayout);
        nav_ocorrenciasLayout.setHorizontalGroup(
            nav_ocorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_ocorrenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nav_ocorrenciasLayout.setVerticalGroup(
            nav_ocorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_ocorrenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_perfil.setBackground(new java.awt.Color(19, 16, 89));
        nav_perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_perfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_perfilMouseExited(evt);
            }
        });

        label_ocorrencias2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_ocorrencias2.setForeground(new java.awt.Color(255, 255, 255));
        label_ocorrencias2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_carteira.png"))); // NOI18N
        label_ocorrencias2.setText("Perfil");

        javax.swing.GroupLayout nav_perfilLayout = new javax.swing.GroupLayout(nav_perfil);
        nav_perfil.setLayout(nav_perfilLayout);
        nav_perfilLayout.setHorizontalGroup(
            nav_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nav_perfilLayout.setVerticalGroup(
            nav_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_contato.setBackground(new java.awt.Color(19, 16, 89));
        nav_contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_contato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_contatoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_contatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_contatoMouseExited(evt);
            }
        });

        label_ocorrencias3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_ocorrencias3.setForeground(new java.awt.Color(255, 255, 255));
        label_ocorrencias3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_contato.png"))); // NOI18N
        label_ocorrencias3.setText("Contato");

        nav_material.setBackground(new java.awt.Color(19, 16, 89));
        nav_material.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_materialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_materialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_materialMouseExited(evt);
            }
        });

        label_ocorrencias4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_ocorrencias4.setForeground(new java.awt.Color(255, 255, 255));
        label_ocorrencias4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_material.png"))); // NOI18N
        label_ocorrencias4.setText("Material");

        javax.swing.GroupLayout nav_materialLayout = new javax.swing.GroupLayout(nav_material);
        nav_material.setLayout(nav_materialLayout);
        nav_materialLayout.setHorizontalGroup(
            nav_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_materialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nav_materialLayout.setVerticalGroup(
            nav_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_materialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout nav_contatoLayout = new javax.swing.GroupLayout(nav_contato);
        nav_contato.setLayout(nav_contatoLayout);
        nav_contatoLayout.setHorizontalGroup(
            nav_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_contatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(nav_material, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nav_contatoLayout.setVerticalGroup(
            nav_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_contatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nav_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nav_contato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_ocorrencias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_frequencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_desempenho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_perfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(nav_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_desempenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_frequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_ocorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(navbar);
        navbar.setBounds(0, 0, 140, 530);

        javax.swing.GroupLayout rendererLayout = new javax.swing.GroupLayout(renderer);
        renderer.setLayout(rendererLayout);
        rendererLayout.setHorizontalGroup(
            rendererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        rendererLayout.setVerticalGroup(
            rendererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(renderer);
        renderer.setBounds(140, 80, 590, 450);

        setSize(new java.awt.Dimension(728, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void setNavColor (JPanel p)
    {
        p.setBackground(new Color(15, 34, 61));
    }

    public void resetNavColor (JPanel p)
    {
        p.setBackground(new Color(19, 16, 89));
    }
    
    private void nav_inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_inicioMouseEntered
        setNavColor(nav_inicio);
    }//GEN-LAST:event_nav_inicioMouseEntered

    private void nav_inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_inicioMouseExited
        resetNavColor(nav_inicio);
    }//GEN-LAST:event_nav_inicioMouseExited

    
    private void nav_desempenhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_desempenhoMouseEntered
        setNavColor(nav_desempenho);
    }//GEN-LAST:event_nav_desempenhoMouseEntered

    private void nav_desempenhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_desempenhoMouseExited
        resetNavColor(nav_desempenho);
    }//GEN-LAST:event_nav_desempenhoMouseExited

    
    private void nav_frequenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_frequenciaMouseEntered
        setNavColor(nav_frequencia);
    }//GEN-LAST:event_nav_frequenciaMouseEntered

    private void nav_frequenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_frequenciaMouseExited
        resetNavColor(nav_frequencia);
    }//GEN-LAST:event_nav_frequenciaMouseExited

    
    
    private void nav_ocorrenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_ocorrenciasMouseEntered
        setNavColor(nav_ocorrencias);
    }//GEN-LAST:event_nav_ocorrenciasMouseEntered

    private void nav_ocorrenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_ocorrenciasMouseExited
        resetNavColor(nav_ocorrencias);
    }//GEN-LAST:event_nav_ocorrenciasMouseExited

    
    private void nav_perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_perfilMouseEntered
        setNavColor(nav_perfil);
    }//GEN-LAST:event_nav_perfilMouseEntered

    private void nav_perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_perfilMouseExited
        resetNavColor(nav_perfil);
    }//GEN-LAST:event_nav_perfilMouseExited

    
    private void nav_contatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_contatoMouseEntered
        setNavColor(nav_contato);
    }//GEN-LAST:event_nav_contatoMouseEntered

    private void nav_contatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_contatoMouseExited

        resetNavColor(nav_contato);
    }//GEN-LAST:event_nav_contatoMouseExited


 
    int x, y;
    private void top_fixed_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_fixed_barMousePressed
        int x = evt.getX();
        int y = evt.getY();
    }//GEN-LAST:event_top_fixed_barMousePressed

    private void top_fixed_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_fixed_barMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_top_fixed_barMouseDragged

    
    private void button_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_closeMouseClicked
        int opt = JOptionPane.showConfirmDialog(rootPane, "Deseja sair do aplicativo?", "Sair", 0);
        if (opt == 0) 
        {
            System.exit(0);
        }
    }//GEN-LAST:event_button_closeMouseClicked

    
    page_inicio inicio = new page_inicio();
    page_perfil perfil = new page_perfil();
    page_desempenho desempenho = new page_desempenho();
    page_frequencia frequencia = new page_frequencia();
    page_ocorrencias ocorrencias = new page_ocorrencias();
    page_contato contato = new page_contato();
    page_material material = new page_material();
    
    private void open_page(Component comp) {
        renderer.removeAll();
        renderer.add(comp).setVisible(true);
    }
    
    private void nav_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_inicioMouseClicked
        open_page(inicio);
    }//GEN-LAST:event_nav_inicioMouseClicked

    private void nav_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_perfilMouseClicked
        open_page(perfil);
    }//GEN-LAST:event_nav_perfilMouseClicked

    private void nav_desempenhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_desempenhoMouseClicked
        open_page(desempenho);
    }//GEN-LAST:event_nav_desempenhoMouseClicked

    private void nav_frequenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_frequenciaMouseClicked
        open_page(frequencia);
    }//GEN-LAST:event_nav_frequenciaMouseClicked

    private void nav_ocorrenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_ocorrenciasMouseClicked
        open_page(ocorrencias);
    }//GEN-LAST:event_nav_ocorrenciasMouseClicked

    private void nav_contatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_contatoMouseClicked
        open_page(contato);
    }//GEN-LAST:event_nav_contatoMouseClicked

    private void nav_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_materialMouseClicked
        open_page(material);
    }//GEN-LAST:event_nav_materialMouseClicked

    private void nav_materialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_materialMouseEntered
        setNavColor(nav_material);
    }//GEN-LAST:event_nav_materialMouseEntered

    private void nav_materialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_materialMouseExited
        resetNavColor(nav_material);
    }//GEN-LAST:event_nav_materialMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel button_close;
    private javax.swing.JLabel button_logout;
    private javax.swing.JLabel label_desempenho;
    private javax.swing.JLabel label_frequencia;
    private javax.swing.JLabel label_inicio;
    private javax.swing.JLabel label_ocorrencias1;
    private javax.swing.JLabel label_ocorrencias2;
    private javax.swing.JLabel label_ocorrencias3;
    private javax.swing.JLabel label_ocorrencias4;
    private javax.swing.JPanel nav_contato;
    private javax.swing.JPanel nav_desempenho;
    private javax.swing.JPanel nav_frequencia;
    private javax.swing.JPanel nav_inicio;
    private javax.swing.JPanel nav_material;
    private javax.swing.JPanel nav_ocorrencias;
    private javax.swing.JPanel nav_perfil;
    private javax.swing.JPanel navbar;
    private javax.swing.JDesktopPane renderer;
    private javax.swing.JLabel top_bar_class;
    private javax.swing.JLabel top_bar_name;
    private javax.swing.JPanel top_fixed_bar;
    // End of variables declaration//GEN-END:variables
}
